name: Test / Apps

on:
  workflow_dispatch:
    inputs:
      env:
        description: "env"
        required: true
        default: "production"
      apps:
        description: "apps"
        required: true
        default: "ruby,node"

permissions:
  contents: read

jobs:
  ruby:
    if: contains(inputs.apps, 'ruby')
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - runs-on=${{ github.run_id }}-ruby,runner=2cpu-linux-x64,env=${{ inputs.env || 'production' }},extras=s3-cache
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: runs-on/test-apps
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          working-directory: ruby/blog
          cache-version: 1

  node:
    if: contains(inputs.apps, 'node')
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - runs-on=${{ github.run_id }}-node,runner=2cpu-linux-x64,env=${{ inputs.env || 'production' }},extras=s3-cache
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: runs-on/test-apps

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: node/nextjs-blog/package-lock.json

      - run: npm install
        working-directory: node/nextjs-blog